import type { Metadata } from "next";
import { Nunito } from "next/font/google"; // Import Nunito
import "./globals.css";
import { AuthProvider } from "@/lib/AuthContext";

// Configure Nunito font
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito", // CSS variable for Nunito
  weight: ["400", "700", "800"], // Specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable}`}> {/* Apply Nunito variable to html tag */}
      <body className="antialiased"> {/* Remove previous font variables, antialiased is good */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}